import argparse
import sys

def print_python_rules(decision_rules_file):
    with open(decision_rules_file) as fh:
        print("\t", "fmsg = ''")
        for line in fh:
            line = line.strip()
            if not line:
                continue
            prepart, rule = line.split("--- ")

            if rule.startswith("class:"):
                print("\t" * prepart.count('|'), "fmsg += '" + rule + "'")
            else:
                print("\t" * prepart.count('|'), "if " + rule + ":")


def parse_input():
    DESC = """
    Usage: %(prog)s <generated_rule_file>
    """
    EXAMPLES = """
    eg: python3 %(prog)s <generated_rule_file>
    python3 %(prog)s rule1_gen.txt
    """
    parser = argparse.ArgumentParser(formatter_class=argparse.RawDescriptionHelpFormatter, description=DESC,
                                   epilog=EXAMPLES)
    parser.add_argument('decision_rules', help='Rules text generated by decision trees')
    if len(sys.argv) < 2:
        parser.parse_args(['-h'])
    args = parser.parse_args()
    return args


def main():
    args = parse_input()
    print_python_rules(args.decision_rules)


if __name__ == "__main__":
  main()
